import AVFoundation
import Foundation
import Testing

@testable import StoryApp
@testable import StoryService

/// I31. Two claims, each with the control the house style asks for:
///
/// 1. **A DRM-protected selection is refused before upload.** The control is a DRM-*free* file
///    that must be accepted — without it, "protected files are refused" would also be true of a
///    check that refuses everything.
/// 2. **The refusal happens before any network call**, proven by never registering a stub host for
///    the protected case: a request that somehow escaped the check would hit an unregistered host
///    and the test would fail loudly rather than silently pass.
///
/// **What this suite cannot prove.** There is no genuine FairPlay-encrypted fixture here — one
/// cannot be manufactured without Apple's own DRM tooling and a store-issued file, and committing
/// a real one would not be legal to redistribute anyway. The `.m4p`-extension path is exercised
/// directly and exactly; the `AVURLAsset.hasProtectedContent` path is real production code,
/// covered only indirectly (a plain file must load and report `false`), and needs a genuine
/// protected fixture from a real device to be exercised end to end. Recorded rather than hidden.
struct MusicImportTests {

    // MARK: - Fixtures

    /// A short, genuinely decodable AAC file, synthesized with `AVAudioFile` rather than shipped
    /// as a binary fixture or generated by shelling out to `ffmpeg` — this runs on any CI host with
    /// no external binary and no committed audio blob.
    private func makeClearAudioFile(named name: String = "track.m4a") throws -> URL {
        let url = FileManager.default.temporaryDirectory.appending(
            path: "MusicImportTests-\(UUID().uuidString)/\(name)")
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true)

        let format = AVAudioFormat(standardFormatWithSampleRate: 44100, channels: 1)!
        let settings: [String: Any] = [
            AVFormatIDKey: kAudioFormatMPEG4AAC,
            AVSampleRateKey: 44100,
            AVNumberOfChannelsKey: 1,
        ]
        let file = try AVAudioFile(forWriting: url, settings: settings)
        let frameCount: AVAudioFrameCount = 4410  // 0.1 s -- plenty for a real, tiny, valid file
        let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: frameCount)!
        buffer.frameLength = frameCount
        if let channel = buffer.floatChannelData?[0] {
            for i in 0..<Int(frameCount) {
                channel[i] = Float(sin(Double(i) * 0.05)) * 0.1
            }
        }
        try file.write(from: buffer)
        return url
    }

    private func makeGarbageFile(named name: String = "not-audio.m4a") throws -> URL {
        let url = FileManager.default.temporaryDirectory.appending(
            path: "MusicImportTests-\(UUID().uuidString)/\(name)")
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try Data("this is not an audio container".utf8).write(to: url)
        return url
    }

    // MARK: - DRMCheck

    @Test func aLegacyProtectedExtensionIsRefusedWithoutOpeningTheFile() async throws {
        // Point ".m4p" at a file that doesn't even exist -- if the check had to open it to decide,
        // this would fail with a file-not-found error instead of a protected-content verdict.
        let url = URL(fileURLWithPath: "/nonexistent/does-not-exist.m4p")
        let verdict = await DRMCheck.check(url: url)
        guard case .protectedContent(let reason) = verdict else {
            Issue.record("expected .protectedContent, got \(verdict)")
            return
        }
        #expect(reason.contains("m4p") || reason.contains(url.lastPathComponent))
    }

    @Test func aRealDRMFreeFileIsClear() async throws {
        // The control for every refusal test in this suite: a real, valid, unprotected audio file
        // must pass, or "protected files are refused" would be true of a check that refuses
        // everything.
        let url = try makeClearAudioFile()
        let verdict = await DRMCheck.check(url: url)
        #expect(verdict == .clear)
    }

    @Test func anUnreadableFileIsFlaggedDistinctlyFromDRM() async throws {
        let url = try makeGarbageFile()
        let verdict = await DRMCheck.check(url: url)
        guard case .unreadable = verdict else {
            Issue.record("expected .unreadable, got \(verdict)")
            return
        }
    }

    // MARK: - MusicImporter: the refusal happens before any network call

    @Test func aProtectedSelectionNeverReachesTheNetwork() async throws {
        let workDir = FileManager.default.temporaryDirectory.appending(
            path: "MusicImportTests-work-\(UUID().uuidString)")
        // Deliberately no stub host registered: if the importer tried to negotiate or upload
        // despite the refusal, the request would hit an unregistered host and this test would see
        // a transport error, not a quiet pass.
        let host = "unregistered-\(UUID().uuidString).invalid"
        let endpoint = ServiceEndpoint(baseURL: URL(string: "https://\(host)")!)
        let identity = UnverifiedIdentityHeader(identity: "traveller@example.com")
        let client = StoryServiceClient(endpoint: endpoint, identity: identity)
        let importer = MusicImporter(client: client, tripID: "trip-1", workingDirectory: workDir)

        let protectedURL = FileManager.default.temporaryDirectory.appending(
            path: "definitely-drm.m4p")

        await #expect(throws: MusicImporter.ImportError.self) {
            _ = try await importer.importTrack(from: protectedURL)
        }
    }

    @Test func aClearTrackIsHashedNegotiatedAndUploaded() async throws {
        let workDir = FileManager.default.temporaryDirectory.appending(
            path: "MusicImportTests-work-\(UUID().uuidString)")
        let fake = MusicFakeService()
        let (endpoint, session, identity) = fake.install()
        defer { fake.uninstall() }

        let client = StoryServiceClient(endpoint: endpoint, identity: identity, session: session)
        let importer = MusicImporter(
            client: client, tripID: "trip-1", workingDirectory: workDir,
            makeTransport: { fake.uploadTransport() })

        let trackURL = try makeClearAudioFile()
        let imported = try await importer.importTrack(from: trackURL)

        #expect(imported.filename == "track.m4a")
        #expect(fake.negotiateCallCount == 1)
        #expect(fake.putCallCount == 1)
        #expect(FileManager.default.fileExists(atPath: workDir.appending(path: "track.m4a").path))
    }
}
